'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace PersonasSvc
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Persona", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Persona
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PersonaIdField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ApellidoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombresField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaNacimientoField As String
        
        Private SexoField As PersonasSvc.SexoEnum
        
        Private AnuladoField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property PersonaId() As String
            Get
                Return Me.PersonaIdField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PersonaIdField, value) <> true) Then
                    Me.PersonaIdField = value
                    Me.RaisePropertyChanged("PersonaId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property Apellido() As String
            Get
                Return Me.ApellidoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ApellidoField, value) <> true) Then
                    Me.ApellidoField = value
                    Me.RaisePropertyChanged("Apellido")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property Nombres() As String
            Get
                Return Me.NombresField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombresField, value) <> true) Then
                    Me.NombresField = value
                    Me.RaisePropertyChanged("Nombres")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property FechaNacimiento() As String
            Get
                Return Me.FechaNacimientoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FechaNacimientoField, value) <> true) Then
                    Me.FechaNacimientoField = value
                    Me.RaisePropertyChanged("FechaNacimiento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=4)>  _
        Public Property Sexo() As PersonasSvc.SexoEnum
            Get
                Return Me.SexoField
            End Get
            Set
                If (Me.SexoField.Equals(value) <> true) Then
                    Me.SexoField = value
                    Me.RaisePropertyChanged("Sexo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=5)>  _
        Public Property Anulado() As Boolean
            Get
                Return Me.AnuladoField
            End Get
            Set
                If (Me.AnuladoField.Equals(value) <> true) Then
                    Me.AnuladoField = value
                    Me.RaisePropertyChanged("Anulado")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SexoEnum", [Namespace]:="http://tempuri.org/")>  _
    Public Enum SexoEnum As Integer

        <System.Runtime.Serialization.EnumMemberAttribute()>
        Masculino = 1

        <System.Runtime.Serialization.EnumMemberAttribute()>
        Femenino = 2
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="PersonasSvc.ServiceSoap")>  _
    Public Interface ServiceSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListadoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Listado", ReplyAction:="*")>  _
        Function Listado(ByVal request As PersonasSvc.ListadoRequest) As PersonasSvc.ListadoResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento persona del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Guardar", ReplyAction:="*")>  _
        Function Guardar(ByVal request As PersonasSvc.GuardarRequest) As PersonasSvc.GuardarResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento persona del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Editar", ReplyAction:="*")>  _
        Function Editar(ByVal request As PersonasSvc.EditarRequest) As PersonasSvc.EditarResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Anular", ReplyAction:="*")>  _
        Function Anular(ByVal id As Integer) As Boolean
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListadoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Listado", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PersonasSvc.ListadoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PersonasSvc.ListadoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class ListadoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ListadoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ListadoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PersonasSvc.ListadoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PersonasSvc.ListadoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ListadoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ListadoResult() As PersonasSvc.Persona
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ListadoResult() As PersonasSvc.Persona)
            MyBase.New
            Me.ListadoResult = ListadoResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GuardarRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Guardar", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PersonasSvc.GuardarRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PersonasSvc.GuardarRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GuardarRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public persona As PersonasSvc.Persona
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal persona As PersonasSvc.Persona)
            MyBase.New
            Me.persona = persona
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GuardarResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GuardarResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PersonasSvc.GuardarResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PersonasSvc.GuardarResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GuardarResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public GuardarResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GuardarResult As Boolean)
            MyBase.New
            Me.GuardarResult = GuardarResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EditarRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Editar", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PersonasSvc.EditarRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PersonasSvc.EditarRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EditarRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public id As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public persona As PersonasSvc.Persona
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal id As Integer, ByVal persona As PersonasSvc.Persona)
            MyBase.New
            Me.id = id
            Me.persona = persona
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EditarResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EditarResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As PersonasSvc.EditarResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As PersonasSvc.EditarResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EditarResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public EditarResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EditarResult As Boolean)
            MyBase.New
            Me.EditarResult = EditarResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ServiceSoapChannel
        Inherits PersonasSvc.ServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of PersonasSvc.ServiceSoap)
        Implements PersonasSvc.ServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PersonasSvc_ServiceSoap_Listado(ByVal request As PersonasSvc.ListadoRequest) As PersonasSvc.ListadoResponse Implements PersonasSvc.ServiceSoap.Listado
            Return MyBase.Channel.Listado(request)
        End Function
        
        Public Function Listado() As PersonasSvc.Persona()
            Dim inValue As PersonasSvc.ListadoRequest = New PersonasSvc.ListadoRequest()
            inValue.Body = New PersonasSvc.ListadoRequestBody()
            Dim retVal As PersonasSvc.ListadoResponse = CType(Me,PersonasSvc.ServiceSoap).Listado(inValue)
            Return retVal.Body.ListadoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PersonasSvc_ServiceSoap_Guardar(ByVal request As PersonasSvc.GuardarRequest) As PersonasSvc.GuardarResponse Implements PersonasSvc.ServiceSoap.Guardar
            Return MyBase.Channel.Guardar(request)
        End Function
        
        Public Function Guardar(ByVal persona As PersonasSvc.Persona) As Boolean
            Dim inValue As PersonasSvc.GuardarRequest = New PersonasSvc.GuardarRequest()
            inValue.Body = New PersonasSvc.GuardarRequestBody()
            inValue.Body.persona = persona
            Dim retVal As PersonasSvc.GuardarResponse = CType(Me,PersonasSvc.ServiceSoap).Guardar(inValue)
            Return retVal.Body.GuardarResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function PersonasSvc_ServiceSoap_Editar(ByVal request As PersonasSvc.EditarRequest) As PersonasSvc.EditarResponse Implements PersonasSvc.ServiceSoap.Editar
            Return MyBase.Channel.Editar(request)
        End Function
        
        Public Function Editar(ByVal id As Integer, ByVal persona As PersonasSvc.Persona) As Boolean
            Dim inValue As PersonasSvc.EditarRequest = New PersonasSvc.EditarRequest()
            inValue.Body = New PersonasSvc.EditarRequestBody()
            inValue.Body.id = id
            inValue.Body.persona = persona
            Dim retVal As PersonasSvc.EditarResponse = CType(Me,PersonasSvc.ServiceSoap).Editar(inValue)
            Return retVal.Body.EditarResult
        End Function
        
        Public Function Anular(ByVal id As Integer) As Boolean Implements PersonasSvc.ServiceSoap.Anular
            Return MyBase.Channel.Anular(id)
        End Function
    End Class
End Namespace
